package com.enviro.assessment.grad001.kamohelolebjane.service;

import java.util.Arrays;
import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.enviro.assessment.grad001.kamohelolebjane.model.CategorizationLookup;
import com.enviro.assessment.grad001.kamohelolebjane.model.Enviro;
import com.enviro.assessment.grad001.kamohelolebjane.repository.*;

import jakarta.annotation.PostConstruct;

@Service
public class EnviroService {
	
	EnviroRep enviroRep;
	CategorizationLookupRep categorizationLookupRep;
	
	 @Autowired
	public EnviroService(EnviroRep enviroRep,CategorizationLookupRep categorizationLookupRep) {
		 /*
		  * This class inputs all information for category lookup, 
		  * disposal guidelines retrieval, and recycling tips display. 
		  */
	    this.enviroRep = enviroRep;
	    this.categorizationLookupRep=categorizationLookupRep;
	    
	    //disposal guidelines
	    List<Enviro> enviro=Arrays.asList(
	    	    new Enviro("Municipal Solid Waste (MSW)","Separate household and commercial waste into recyclables, compostables, and trash; use designated bins for each type.","Recycle household items such as paper, cardboard, plastic bottles, and glass jars by cleaning them and placing them in the correct recycling bins."),
	    	    new Enviro("Hazardous Waste","Take hazardous waste, including e-waste, to designated collection centers for safe disposal.","Recycle e-waste like old computers and phones at certified e-waste recycling centers, and ensure batteries are taken to specialized recycling points."),
	    	    new Enviro("Construction and Demolition Waste (C&D)","Transport C&D waste to specialized facilities that can handle recycling or safe disposal of construction materials.","Separate materials like wood, metal, and concrete on-site for recycling; many materials can be repurposed or processed for new construction projects."),
	    	    new Enviro("Agricultural Waste","Compost organic agricultural waste on-site and safely dispose of expired pesticides at hazardous waste facilities.","Compost organic waste such as plant residues and animal manure to create natural fertilizer, reducing the need for chemical inputs."),
	    	    new Enviro("Industrial Waste","Ensure industrial waste is treated and disposed of according to regulatory standards, often requiring specialized treatment plants.","Implement a recycling program within the industry to recover and reuse materials such as scrap metal, paper, and certain chemicals."),
	    	    new Enviro("Radioactive Waste","Store radioactive waste in secure, licensed facilities designed to handle low-level and high-level radioactive materials.","While recycling radioactive materials is highly specialized, some low-level waste can be processed and repurposed under strict regulatory controls."),
	    	    new Enviro("Organic Waste","Compost food and green waste to create nutrient-rich soil amendments instead of sending it to landfills.","Set up a composting system for food scraps and yard waste to produce compost that can be used in gardens and landscaping."),
	    		new Enviro("Recyclable Waste","Clean and sort recyclables like paper, plastic, glass, and metal before placing them in the appropriate recycling bins.","Rinse and sort recyclables like paper, plastics, metals, and glass; ensure they are free from food and contaminants before recycling."),
	    		new Enviro("Recyclable Waste","Schedule a special collection or take bulk waste items like furniture and appliances to local disposal or recycling centers.","Donate large items like furniture and appliances if they are in good condition, or find local programs that dismantle and recycle parts."),
	    		new Enviro("Special Waste","Drop off tires, batteries, and used oil at designated recycling or disposal facilities to prevent environmental contamination.","Take used tires to tire recycling centers where they can be processed into new products, and recycle used oil at service stations or collection points to be re-refined into new oil.")
	    	    );
    
	    enviroRep.saveAll(enviro);
	    
	    //categories, it includes extra information on how to identity which waste belongs to a certain category
	    List<CategorizationLookup> categorizationLookup=Arrays.asList(
	    new CategorizationLookup(enviro.get(0),"Household Waste: Includes everyday items such as product packaging, furniture, clothing, bottles, food scraps, newspapers, appliances, paint, and batteries."),
	    new CategorizationLookup(enviro.get(0),"Commercial Waste: Generated by businesses such as offices, stores, and restaurants."),
	    new CategorizationLookup(enviro.get(1),"Industrial Waste: Byproducts of manufacturing and industrial processes that may contain toxic chemicals, heavy metals, or other hazardous substances."),
	    new CategorizationLookup(enviro.get(1),"Medical Waste: Includes sharps, expired pharmaceuticals, contaminated supplies, and biohazardous materials from hospitals and clinics."),
	    new CategorizationLookup(enviro.get(1),"E-Waste: Discarded electronic devices such as computers, phones, televisions, and batteries containing hazardous materials like lead, mercury, and cadmium."),
	    new CategorizationLookup(enviro.get(2),"Construction Waste: Includes wood, concrete, bricks, metal, and glass from building sites."),
	    new CategorizationLookup(enviro.get(2),"Demolition Waste: Material resulting from the destruction of buildings or structures."),
	    new CategorizationLookup(enviro.get(3),"Organic Waste: Plant residues, animal manure, and other organic matter."),
	    new CategorizationLookup(enviro.get(3),"Pesticides and Herbicides: Chemicals used in farming that can become waste when expired or unused."),
	    new CategorizationLookup(enviro.get(4),"Process Waste: Byproducts from the manufacturing process, including scrap materials, chemicals, and wastewater."),
	    new CategorizationLookup(enviro.get(4),"Sludge: Semi-solid waste produced by industrial wastewater treatment plants"),
	    new CategorizationLookup(enviro.get(5),"Low-Level Waste: Contaminated protective clothing, tools, and other materials with low levels of radioactivity."),
	    new CategorizationLookup(enviro.get(5),"High-Level Waste: Spent nuclear fuel and waste materials from nuclear reactors."),
	    new CategorizationLookup(enviro.get(6),"Food Waste: Spoiled or uneaten food from households, restaurants, and food processing plants."),
	    new CategorizationLookup(enviro.get(6),"Green Waste: Yard trimmings, grass clippings, leaves, and other garden waste."),
	    new CategorizationLookup(enviro.get(7),"Paper and Cardboard: Newspapers, magazines, boxes, and office paper"),
	    new CategorizationLookup(enviro.get(7),"Plastic: Bottles, containers, and packaging materials."),
	    new CategorizationLookup(enviro.get(7),"Glass: Bottles and jars."),
	    new CategorizationLookup(enviro.get(7),"Metal: Cans, foil, and scrap metal"),
	    new CategorizationLookup(enviro.get(8),"Large Items: Furniture, mattresses, and large appliances not suitable for regular waste collection."),
	    new CategorizationLookup(enviro.get(9),"Tires: Old and used tires."),
	    new CategorizationLookup(enviro.get(9),"Batteries: Household and automotive batteries"),
	    new CategorizationLookup(enviro.get(9),"Used Oil: Motor oil and lubricants.")
	    );
	    
	    categorizationLookupRep.saveAll(categorizationLookup);
	    
	   
	    
	}
	 //Gets all categories
	 public List<String> getCategories() {
		 return enviroRep.findAllCategories();
	 }
	/*Gets all categories along with the additional information that allows you to 
	 * identify which waste belongs to certain category
	 */
	 public List<String> allCategorizationLookupinfo(){
		 return categorizationLookupRep.AllCategoriesandIdentificationInfo();
	 }
	 //Retrieves disposal guidlines
	 public List<String> disposalGuidlines(){
		  return enviroRep.findDisposalGuidlines();
	 }
	 //Retrieves Recycle tips
	 public List<String> findRecyclingTips(){
		 return enviroRep.findRecyclingTips();
	 }
	 //Helps you update a recycle tip
	 public int updateRecyTipByID(long id,String recyTips) {
		 return enviroRep.updateRecyclingTips(id, recyTips);
	 }
	 //Deletes the extra information pertaining to the category
	 public int deleteItemIdentificationInfoById(long id){
		 return categorizationLookupRep.deleteItemIdentificationInfoById(id);
	 }
	 /*	
	  * This returns all information(categories, disposal guidlines and recycle tips)
	  */
	 public List<Enviro> allinfo(){
		 return enviroRep.findAll();
	 }
	
}
